JmanOps/urls.py
"""
Definition of urls for JmanOps.
"""

from datetime import datetime
from django.conf.urls import include, url
import django.contrib.auth.views
import app.forms
import app.views
from django.contrib import admin





# Uncomment the next lines to enable the admin:
#from django.conf.urls import include
#from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^contact-list$', app.views.ContactList),
    url(r'^currency-list$', app.views.CurrencyList, name='currency-list'),
    url(r'^UpdateCurrencyTable$', app.views.UpdateCurrencyTable, name='UpdateCurrencyTable'),
    url(r'contact-edit/(?P<pk>[0-9]+)/$', app.views.ContactUpdateView.as_view(), name='contact-edit'),
    url(r'^contact-create/$', app.views.ContactCreateView.as_view(), name='contact-create'),
    url(r'contact-save-edit/$', app.views.contact_edit, name='contact-save-edit'),
    url(r'contact-delete/$', app.views.delete_contact, name='contact-delete'),
    url(r'^create_contactPost/$', app.views.add_new_contact_view),
    url(r'^search/', app.views.customer_search),
    url(r'^lookup/', app.views.customer_lookup),

    url(r'^order2$', app.views.order2.as_view(),name='order2'),
    url(r'^order-list$', app.views.OrderList,name='order-list'),
    url(r'order/(?P<pk>[0-9]+)/$', app.views.SOrderUpdate.as_view(), name='order-update'),
    url(r'order-delete/(?P<pk>[0-9]+)/delete/$', app.views.SOrderDelete, name='order-delete'),
    url(r'order-print/(?P<pk>[0-9]+)/$', app.views.CreatePdfTestView, name='order-print'),
    url(r'order-docprint/(?P<pk>[0-9]+)/$', app.views.write_pdf_view_doc, name='order-docprint'),
    url(r'^setcurrency/$', app.views.setCurrency,name='setcurrency'),
    url(r'^setXRate/$', app.views.setCurrencyRate,name='setXRate'),
    #needed for edit of order to get ajax script to work
    url(r'^order/\d/setcurrency/$', app.views.setCurrency,name='setcurrency'),
    url(r'^order/\d/setXRate/$', app.views.setCurrencyRate,name='setXRate'),

    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.home, name='contact'),
    url(r'^about', app.views.home, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    

    url(r'^customer$', app.views.CustomerView.as_view(), name='customer'),
    url(r'^search/', app.views.customer_search),
    url(r'^customer_move/$', app.views.customer_move),
    url(r'^customer_trans/$', app.views.customer_trans),
    #url(r'^customer_move/$', app.views.CustomerMoveView.as_view(), name='customer_move'),
    url(r'^create_custpost/$', app.views.create_custpost),
    url(r'^delete_customer/$', app.views.delete_customer),

    url(r'^getXeroPayments/$', app.views.get_Xero_Receipts, name='getXeroPayments'),
    url(r'^XeroInvoice/(?P<pk>[0-9]+)/$', app.views.add_Xero_invoice, name='XeroInvoice'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', admin.site.urls),
]

app/models.py
"""
Definition of models.
"""
from __future__ import unicode_literals
#from django.core.urlresolvers import reverse

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


import datetime
#from app.models import Currency
from django.forms.models import BaseInlineFormSet

# Create your models here.
class SYSTEM_SEQCONTRL(models.Model):
    CTL_TABLE = models.CharField(max_length=128,default='',blank=True)
    CTL_FIELD = models.CharField(max_length=128,default='',blank=True)
    CTL_SEQ_NUMBER = models.IntegerField(default=0,blank=False)
    CTL_SEQ_LAST_INTEGRATION_DATEIME = models.DateTimeField()


    class Meta:
        unique_together = ('CTL_TABLE', 'CTL_FIELD',)

    def __str__(self):
        return self.CTL_TABLE+','+self.CTL_FIELD+': '+str(self.CTL_SEQ_NUMBER)



class Currency(models.Model):
    Code = models.CharField(unique=True,max_length=3,default='',blank=False)
    Name = models.CharField(max_length=100,default='',blank=True)
    Symbol = models.CharField(max_length=4,default='',blank=True,null=True)
    Entered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Code+': '+self.Name

class ExchangeRates(models.Model):
    Code = models.CharField(max_length=3,default='',blank=False)
    Name = models.CharField(max_length=100,default='',blank=True)
    ExRate = models.FloatField(default=1,null=True)
    RateDate = models.DateField(auto_now_add=True)
    Entered = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = ('Code', 'RateDate',)

    def __str__(self):
        return self.Code+': '+str(self.ExRate)

class SYSTEM_MAIN(models.Model):
    CompanyName = models.CharField(max_length=128,default='',blank=True)
    Address = models.TextField(max_length=160,default='',null=True,blank=True)
    Town = models.CharField(max_length=20,default='',blank=True)
    County = models.CharField(max_length=20,default='',blank=True)    
    PostCode = models.CharField(max_length=12,null=True,default='',blank=True)
    Country = models.CharField(max_length=20,default='',blank=True)
    Phone = models.CharField(max_length=20,default='',blank=True)
    Mobile = models.CharField(max_length=20,default='',blank=True)
    Email = models.CharField(max_length=64,default='',blank=True)
    Website = models.CharField(max_length=64,default='',blank=True)
    Curency=models.ForeignKey(Currency,on_delete=models.DO_NOTHING)
    CoVatNo = models.CharField(max_length=15,default='',blank=True)
    CoRegNo = models.CharField(max_length=20,default='',blank=True)

    def __str__(self):
        return self.CompanyName


class SYSTEM_BANK(models.Model):
    BankType=models.CharField(max_length=20,default='',blank=True)    
    Curency=models.ForeignKey(Currency,on_delete=models.DO_NOTHING)
    AccountName=models.CharField(max_length=128,default='',blank=True)
    BankName=models.CharField(max_length=128,default='',blank=True)
    BankSortCode=models.CharField(max_length=10,default='',blank=True)
    BankAccountNo=models.CharField(max_length=15,default='',blank=True)
    BankRef=models.CharField(max_length=18,default='',blank=True)
    BankIBAN=models.CharField(max_length=100,default='',blank=True)
    Address = models.TextField(max_length=160,default='',null=True,blank=True)
    Town = models.CharField(max_length=20,default='',blank=True)
    County = models.CharField(max_length=20,default='',blank=True)    
    PostCode = models.CharField(max_length=12,null=True,default='',blank=True)
    Country = models.CharField(max_length=20,default='',blank=True)

    def __str__(self):
        return self.BankType+': '+self.BankName

class Customer(models.Model):
    Code = models.CharField(unique=True,max_length=10,default='',blank=False,db_index=True)
    currency_code=models.CharField(max_length=3,default='',blank=True)
    Name = models.CharField(max_length=100,default='',null=True,blank=True,db_index=True)
    Address = models.TextField(default='',null=True,blank=True)
    Town = models.CharField(max_length=20,default='',null=True,blank=True)
    County = models.CharField(max_length=20,default='',null=True,blank=True)    
    PostCode = models.CharField(max_length=12,null=True,default='',blank=True)
    Country = models.CharField(max_length=20,default='',null=True,blank=True)
    Email = models.CharField(max_length=64,default='',null=True,blank=True)
    Website = models.CharField(max_length=64,default='',null=True,blank=True)
    CoVatNo = models.CharField(max_length=15,default='',null=True,blank=True)
    CoRegNo = models.CharField(max_length=20,default='',null=True,blank=True)
    Entered = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now=True)
    XeroContactID = models.CharField(default='',max_length=64,null=True,db_index=True)
    XeroUpdateFail = models.BooleanField(default=False,db_index=True)
    

    def __str__(self):
        return self.Code+': '+self.Name

class Contact(models.Model):
    ContactNumber = models.IntegerField(default=0,blank=False)
    RecordCode = models.CharField(max_length=10,default='',blank=False)
    RecordType = models.CharField(max_length=20,default='',blank=True)
    ContactType = models.CharField(max_length=20,default='',blank=True)
    Name = models.CharField(max_length=100,default='',blank=True)
    Phone = models.CharField(max_length=20,default='',blank=True)
    Mobile = models.CharField(max_length=20,default='',blank=True)
    Email = models.CharField(max_length=64,default='',blank=True)
    CCEmail = models.CharField(max_length=64,default='',blank=True)
    Address = models.TextField(max_length=160,default='',null=True,blank=True)
    Town = models.CharField(max_length=20,default='',blank=True)
    County = models.CharField(max_length=20,default='',blank=True)    
    PostCode = models.CharField(max_length=12,null=True,default='',blank=True)
    Country = models.CharField(max_length=20,default='',blank=True)
    EnteredBy = models.ForeignKey(User,'None')
    Updated = models.DateTimeField(auto_now=True)
    Created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Code+': '+self.Name

class Item(models.Model):
    Code = models.CharField(unique=True,max_length=10,default='',blank=False)
    Name = models.CharField(max_length=100,default='',blank=True)
    SalesPrice = models.DecimalField(max_digits=20, decimal_places=2)
    CostPrice = models.DecimalField(max_digits=20, decimal_places=2)
    Entered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Code+': '+self.Name

class Analysis(models.Model):
    Code = models.CharField(unique=True,max_length=10,default='',blank=False)
    Name = models.CharField(max_length=100,default='',blank=True)
    Entered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Code+': '+self.Name

class VAT(models.Model):
    Code = models.CharField(unique=True,max_length=10,default='',blank=False)
    Name = models.CharField(max_length=100,default='',blank=True)
    VATRate = models.FloatField()
    Entered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Code

class SoHeader(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.DO_NOTHING) 
    date = models.DateTimeField(auto_now=True)
    order_date = models.DateField(default=datetime.date.today)
    required_date = models.DateField(default=datetime.date.today)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    account = models.CharField(default='',null=True,blank=True,max_length=10)
    SONumber = models.PositiveIntegerField()
    SOReference = models.CharField(default='',null=True,blank=True,max_length=20)    
    SOCurrency = models.ForeignKey(Currency,on_delete=models.DO_NOTHING, related_name = 'tocurrency',default='',null=True)
    SOCurrencycode = models.CharField(default='',null=True,blank=True,max_length=3)
    SOExRate = models.FloatField(default=1,null=True)
    SODescription = models.CharField(default='',null=True,blank=True,max_length=160)

    def __str__(self):
        return self.account+': '+str(self.SONumber)+': '+str(self.order_date)

# Create your models here.
class SoDetail2(models.Model):
    soheader = models.ForeignKey(SoHeader,on_delete=models.DO_NOTHING, related_name = 'tosoheader') 
    account = models.CharField(default='',null=True,blank=True,max_length=10)
    SONumber = models.PositiveIntegerField(default=0,null=True)
    SOLineNumber = models.PositiveIntegerField(default=0)
    item=models.ForeignKey(Item,on_delete=models.DO_NOTHING, related_name = 'toitem')
    itemcode = models.CharField(default='',null=True,blank=True,max_length=10)
    SODetail = models.TextField(default='',null=True,blank=True,max_length=240)
    SOQty = models.FloatField(default=0,null=True)
    SOSalesPrice = models.DecimalField(default=0,max_digits=20, decimal_places=2)
    SONet = models.DecimalField(default=0,max_digits=20, decimal_places=2)
    SOVat = models.DecimalField(default=0,max_digits=20, decimal_places=2)
    SOHomeNet = models.DecimalField(default=0,max_digits=20, decimal_places=2)
    analysis=models.ForeignKey(Analysis,on_delete=models.DO_NOTHING, related_name = 'toanalysis') 
    analysiscode = models.CharField(default='',null=True,blank=True,max_length=10)
    vat=models.ForeignKey(VAT,on_delete=models.DO_NOTHING,null=True,blank=True, related_name = 'tovat')
    vatcode = models.CharField(default='',null=True,blank=True,max_length=10)


class CustomInlineFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super(CustomInlineFormSet, self).__init__(*args, **kwargs)
    def clean(self):
        super(CustomInlineFormSet, self).clean()

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/layout - Copy (2).html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'app/content/datetimepicker/bootstrap-datepicker.js' %}">


    <style>
    .dropdown-submenu {
        position: relative;
    }

    .dropdown-submenu .dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -1px;
    }
    </style>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>




</head>

<body>


    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="https://dkvf7eqydjaua.cloudfront.net/static/img/mainsite/journeymantv_logo_header.png"/></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Customers
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="{% url 'customer' %}">Customer Records</a></li>
                          <!--<li><a href="#">Debtors</a></li>-->
                          <li><a href="{% url 'order2' %}">Orders</a></li>
                          <li><a href="{% url 'order-list' %}">Order List</a></li>
                          <li><a href="#">Invoices</a></li>
                          <li><a href="#">Receipts</a></li>
                          <li><a href="{% url 'currency-list' %}">Currency</a></li>
                            <li><a href="{% url 'UpdateCurrencyTable' %}">Update Currency</a></li>
                        </ul>
                        currency-list
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Owners
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Owner Records</a></li>
                          <!--<li><a href="#">Owner Creditors</a></li>-->
                          <li><a href="#">Statements</a></li>
                          <li><a href="#">Payments</a></li>
                          <li><a href="#">Reports</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Media
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Title Records</a></li>
                          <li><a href="#">Territory Sales</a></li>
                          <li><a href="#">Reports</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Reports
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu" id="Reports">
                        <li class="dropdown-submenu">
                            <a class="test" href="#">Customers<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Aged Debt</a></li>
                                <li><a href="#">Billing</a></li>
                            </ul>
                          </li>
                          <li class="dropdown-submenu">
                            <a class="test" href="#">Owners<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Aged Creditor</a></li>
                                <li><a href="#">Statments</a></li>
                            </ul>
                          </li>
                          <li><a href="#">Titles</a></li>
                          <li><a href="#">Aged Creditor</a></li>
                        </ul>
                    </li>

                    <li><a href="{% url 'contact' %}">Pay-per-View</a></li>
                    <li><a href="{% url 'home' %}">Portal</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>

                </ul>
                {% include 'app/loginpartial.html' %}
 
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}

        <footer>
            <!--<p>&copy; {{ year }} - My Django Application</p>-->
        </footer>
    </div>



    <script src="{% static 'app/scripts/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'app/scripts/jquery.serialize-object.min.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    <script src="{% static 'app/scripts/main.js' %}"></script>
    <script src="{% static 'app/scripts/CustomerRecord.js' %}"></script>    
    <script src="{% static 'app/scripts/moment.js' %}"></script>
    <script src="{% static 'app/scripts/datetimepicker/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'app/scripts/datetimepicker/locales/bootstrap-datetimepicker.uk.js' %}"></script>
    <script src="{% static 'app/scripts/datetimepicker/locales/bootstrap-datetimepicker.fr.js' %}"></script>




    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



    <script>

    $('#Reports li').hover(
            function() {
                 //console.log('hover over');
                 $(this).find('ul').show();
            },
            function() {
                 //console.log('hover out');
                  $(this).find('ul').hide();
        });  

   
    </script>

    <script>
        $(function () {
            $("#id_order_date").datepicker({
                minDate: new Date(2007, 1 - 1, 1)
                ,dateFormat: "dd MM yy"
            });            
      } );
    </script>

    <script type="text/javascript">
    $(function () {
        $('#id_required_date').datetimepicker({
        language:  'uk',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		minView: 2,
		forceParse: 0
        });
    });
</script>



{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/jquery-ui.min.css' %}" />
    <link rel="stylesheet" href="{% static 'app/content/datetimepicker/bootstrap-datepicker.js' %}">


    <style>
    .dropdown-submenu {
        position: relative;
    }

    .dropdown-submenu .dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -1px;
    }
    </style>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>




</head>

<body>


    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="{% static 'app/images/jman_logo.png' %}"/></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Customers
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="{% url 'customer' %}">Customer Records</a></li>
                          <!--<li><a href="#">Debtors</a></li>-->
                          <li><a href="{% url 'order2' %}">Orders</a></li>
                          <li><a href="{% url 'order-list' %}">Order List</a></li>
                          <li><a href="#">Invoices</a></li>
                          <li><a href="#">Receipts</a></li>
                          <li><a href="{% url 'currency-list' %}">Currency</a></li>
                            <li><a href="{% url 'UpdateCurrencyTable' %}">Update Currency</a></li>
                        </ul>
                        currency-list
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Owners
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Owner Records</a></li>
                          <!--<li><a href="#">Owner Creditors</a></li>-->
                          <li><a href="#">Statements</a></li>
                          <li><a href="#">Payments</a></li>
                          <li><a href="#">Reports</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Media
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Title Records</a></li>
                          <li><a href="#">Territory Sales</a></li>
                          <li><a href="#">Reports</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Reports
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu" id="Reports">
                        <li class="dropdown-submenu">
                            <a class="test" href="#">Customers<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Aged Debt</a></li>
                                <li><a href="#">Billing</a></li>
                            </ul>
                          </li>
                          <li class="dropdown-submenu">
                            <a class="test" href="#">Owners<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Aged Creditor</a></li>
                                <li><a href="#">Statments</a></li>
                            </ul>
                          </li>
                          <li><a href="#">Titles</a></li>
                          <li><a href="#">Aged Creditor</a></li>
                        </ul>
                    </li>

                    <li><a href="{% url 'contact' %}">Pay-per-View</a></li>
                    <li><a href="{% url 'home' %}">Portal</a></li>
                    <li><a href="{% url 'getXeroPayments' %}">Get Xero</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>

                </ul>
                {% include 'app/loginpartial.html' %}
 
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}

        <footer>
            <!--<p>&copy; {{ year }} - My Django Application</p>-->
        </footer>
    </div>


    <script src="{% static 'app/scripts/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'app/scripts/jquery.serialize-object.min.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    <script src="{% static 'app/scripts/main.js' %}"></script>
    <script src="{% static 'app/scripts/CustomerRecord.js' %}"></script>    
    <script src="{% static 'app/scripts/moment.js' %}"></script>
    <script src="{% static 'app/scripts/datetimepicker/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'app/scripts/datetimepicker/locales/bootstrap-datetimepicker.uk.js' %}"></script>
    <script src="{% static 'app/scripts/datetimepicker/locales/bootstrap-datetimepicker.fr.js' %}"></script>



    <script src="{% static 'app/scripts/jquery-ui-1.12.1.js' %}"></script>




    <script>

    $('#Reports li').hover(
            function() {
                 //console.log('hover over');
                 $(this).find('ul').show();
            },
            function() {
                 //console.log('hover out');
                  $(this).find('ul').hide();
        });  

   
    </script>

    <script>
        $(function () {
            $("#id_order_date").datepicker({
                minDate: new Date(2007, 1 - 1, 1)
                ,dateFormat: "dd MM yy"
            });            
      } );
    </script>

    <script type="text/javascript">
    $(function () {
        $('#id_required_date').datetimepicker({
        language:  'uk',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		minView: 2,
		forceParse: 0
        });
    });
</script>



{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/loginpartial.html
<ul class="nav navbar-nav navbar-right">
    <li><a href="/admin">Administration</a></li>
</ul>
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}